name: "NoLongerEvil HomeAssistant"
description: "No Longer Evil Nest 2nd Gen API"
version: "0.0.1"
slug: "nolongerevil"
init: false
ingress: true
ingress_port: 9543
hassio_api: true
hassio_role: default
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  9543/tcp: 9543
